### ISSUE TITLE
where to change if I dont want download the dataset again and again?

### ISSUE THREAD

**Issue by skanel** [tarun-bisht/tensorflow-scripts#1]
where to change if I dont want download the dataset again and again?

**Comment by tarun-bisht** [comment]
Data is downloading in the part  
`data=tf.keras.datasets.mnist
(x_train,y_train),(x_test,y_test)=mnist.load_data()
`
In most cases, this data will be cached so that it will not download every time, but if you want to cache data locally use 
`mnist.load_data(path='mnist.npz')`
where "path=where to cache the dataset locally"
follow up this link for more help [mnist.load_data()](https://www.tensorflow.org/api_docs/python/tf/keras/datasets/mnist/load_data)
